plugins { id "com.android.application" }

android {
    namespace "top.clrv.fla"
    compileSdk 34
    defaultConfig {
        applicationId "top.clrv.fla"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }
    signingConfigs {
        fla {
            storeFile file("../keystore/fla.p12")
            storeType "pkcs12"
            storePassword "flafla"
            keyAlias "fla"
            keyPassword "flafla"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.fla
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

